os: windows
language: rust
rust:
  - stable
sudo: enabled
branches:
  only:
  - master

cache:
  - cargo
  - directories:
    - ./html/node_modules

before_install:
  - choco install nodejs.install
  - refreshenv

before_script:
  - cd html
  - npm i

script:
  - cd html
  - npm run build
  - npm run pack
  - cd..
  - cargo build --verbose
