os: windows
language: 
  - rust
  - node_js
rust:
  - stable
sudo: enabled
branches:
  only:
  - master

cache:
  - cargo
  - npm
  - directories:
    - ./html/node_modules

before_script:
  - cd html
  - npm i

script:
  - npm run build
  - npm run pack
  - cd..
  - cargo build --verbose
